### PR TITLE
Fix usage from Xcode

### LINKED ISSUE #1: `fatalError` is being used instead of `exit(1)`. The latter is more correct for CLI tools

### LINKED ISSUE #2: When building from Xcode, the Xcode DerivedData dir is being used and messes up the working directory

### PR DESCRIPTION
**Pull request by Joannis**
Fixed #1 and fixes #2

### CODE REVIEW

File: Sources/Droidy/Tools/SDK.swift [hunk 1]
```diff
@@ -96,7 +96,7 @@ class SDK {
         print("sdkFolder.path: \(sdkFolder.path)")
         print("tools: \(cmdLineToolsBinFolder.appendingPathComponent("sdkmanager").path)")
         process.currentDirectoryPath = sdkFolder.path
-        process.arguments = ["bash", "-c", "yes | " + cmdLineToolsBinFolder.appendingPathComponent("sdkmanager").path + " --install \"platforms;android-\(droidy.project.compileSdkVersion)\" \"build-tools;\(buildToolsVersionToInstall)\" --sdk_root=" + sdkFolder.path]
```
Comment (MihaelIsaev) [inline Sources/Droidy/Tools/SDK.swift:99]: @Joannis are you sure that `build-tools` should be replaced with `platform-tools`?

Comment (Joannis) [reply Sources/Droidy/Tools/SDK.swift:99]: I didn't replace build-tools, I merely *added* `platform-tools`

Comment (Joannis) [reply Sources/Droidy/Tools/SDK.swift:99]: Those were not yet installed but requires for `adb`
